<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_click here or drop files to upload or transfer(Max 50 files, 10 GB per file, total 50 GB)</name>
   <tag></tag>
   <elementGuidId>8606378c-6302-4321-b7ca-a3f138670c1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.dz-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>111529ee-a70a-401d-99d6-2ed235f1fcef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dz-button</value>
      <webElementGuid>9b5e843e-e153-468a-9fd8-3401db47cf04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c429fa81-fb5c-46a5-af8b-e278782f05f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>click here or drop files to upload or transfer(Max 50 files, 10 GB per file, total 50 GB)</value>
      <webElementGuid>382bf2a1-d751-4c84-9933-36d12f172c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropzone&quot;)/div[@class=&quot;dz-default dz-message&quot;]/button[@class=&quot;dz-button&quot;]</value>
      <webElementGuid>b0f484bb-b1c8-40e9-9380-1e0c17d1da21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>ffd89951-2609-4271-aaaf-62b3e6349bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dropzone']/div[2]/button</value>
      <webElementGuid>06618519-acde-44db-82c6-69618aa15d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Speed'])[1]/following::button[1]</value>
      <webElementGuid>5c20bd4b-7a07-42d2-8ae8-a7e638d2908f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Progress'])[1]/following::button[1]</value>
      <webElementGuid>5e518597-7420-450c-ae65-4b11e48a4826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your file has been uploaded successfully.'])[1]/preceding::button[1]</value>
      <webElementGuid>6d2aa322-7634-4080-83db-8e2adf4630cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='click here or drop files to upload or transfer']/parent::*</value>
      <webElementGuid>94b20527-1aff-496b-a29c-43b828f881c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>dca5d361-a70b-440e-98bc-1807c1df5034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'click here or drop files to upload or transfer(Max 50 files, 10 GB per file, total 50 GB)' or . = 'click here or drop files to upload or transfer(Max 50 files, 10 GB per file, total 50 GB)')]</value>
      <webElementGuid>01217386-858d-4af0-b8d4-1fe5eb18ef66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
